name = "calendar-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
account_id = "0d3d5c5a62f6a8da2b5d7058abbab5cb"

[durable_objects]
bindings = [
  { name = "BOOKING", class_name = "BookingDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BookingDO"]

[vars]
ALLOWED_ORIGIN = "https://www.paralelnapoliskosice.sk"

# Set via `wrangler secret put BTCPAY_WEBHOOK_SECRET`
