[build]
  publish = "public/"
  command = "npm run build"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://paralelnapoliskosice.netlify.com/*"
  to = "https://www.paralelnapoliskosice.sk/:splat"
  status = 301
  force = true

# Check results https://securityheaders.com
[[headers]]
  for = "/*"
  [headers.values]
    # Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self'"
    Feature-Policy = "camera 'none'; microphone 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sw.js" # Gatsby's default service worker file path
  [headers.values]
    Cache-Control = "no-cache"
