[build]
  publish = "public/"
  command = "npm run build"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://paralelnapoliskosice.netlify.com/*"
  to = "https://www.paralelnapoliskosice.sk/:splat"
  status = 301
  force = true
